# Generated by Django 5.0.6 on 2025-06-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apellido_paterno", models.CharField(max_length=50)),
                ("apellido_materno", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=50)),
                ("matricula", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("puntos", models.PositiveIntegerField(default=0)),
                (
                    "alumnos",
                    models.ManyToManyField(
                        blank=True, related_name="equipos", to="equipos.alumno"
                    ),
                ),
            ],
        ),
    ]
