# Generated by Django 5.0.6 on 2025-06-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(blank=True, help_text='Código opcional de la materia', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='año_de_generacion',
            field=models.PositiveIntegerField(default=1, help_text='Ejemplo: 2021', verbose_name='Año de generación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='equipos', to='equipos.materia'),
        ),
    ]
