# Generated by Django 5.0.6 on 2025-07-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_materia_alumno_año_de_generacion_equipo_materias'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submaterias', to='equipos.materia')),
            ],
            options={
                'verbose_name': 'Sub-materia',
                'verbose_name_plural': 'Sub-materias',
                'unique_together': {('materia', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('ponderacion', models.PositiveSmallIntegerField(default=1, help_text='Peso relativo en el cálculo del promedio')),
                ('submateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='equipos.submateria')),
            ],
            options={
                'ordering': ('fecha_entrega',),
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Ej.: 8.5, 10.0', max_digits=5)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='equipos.actividad')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='equipos.alumno')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'unique_together': {('actividad', 'alumno')},
            },
        ),
    ]
